### ISSUE TITLE
RxTextView.textChanges crashes with java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by lennonpetrick** [JakeWharton/RxBinding#452] opened 2018-07-27 14:38 UTC
Hi everyone.

 I have a code like:

    RxTextView
        .textChanges(editText)
        .take(2)
        .subscribe());

And my EditText has another `TextWatcher` in order to format its text.

When I type the first character in the EditText, it throws an `IndexOutOfBoundsException: Invalid index 2, size is 2`.

I figured out that my `TextWatcher` is making the textChanges' observable emit 2 events.
The first disposes the observable and it unregisters the textChanges listener. And when the second is triggered it throws the exception, since the listener isn't anymore in the EditText's arraylist.

**Comment by JakeWharton** [comment] 2018-07-27 14:44
Dupe of #192. This is a platform bug.

**Closed by JakeWharton** 2018-07-27 14:44 UTC
