### ISSUE TITLE
RxTabLayout.selectionEvents() crashes when using Material design library 1.1.0-alpha01 or higher

### ISSUE THREAD

**Issue by JasonAndujar** [JakeWharton/RxBinding#497] opened 2019-01-27 23:00 UTC
```
Caused by: java.lang.ClassCastException: com.jakewharton.rxbinding3.material.TabLayoutSelectionEventObservable$Listener cannot be cast to com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener
        at com.jakewharton.rxbinding3.material.TabLayoutSelectionEventObservable.subscribeActual(TabLayoutSelectionEventObservable.kt:38)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
```
Note this only occurs when updating the material design library higher than 1.0.0

**Comment by JakeWharton** [comment] 2019-01-27 23:16
Dupe of #495

**Closed by JakeWharton** 2019-01-27 23:16 UTC
