### ISSUE TITLE
TabLayout selections has an error

### ISSUE THREAD

**Issue by tcqq** [JakeWharton/RxBinding#495] opened 2018-12-22 03:15 UTC
@JakeWharton Calling TabLayout's `selections` will cause an error. How can I fix this?

Version:
`rxbinding:3.0.0-alpha2`

Code:
```
        tab_layout
                .selections()
                .compose(bindUntilEvent(FragmentEvent.DESTROY_VIEW))
                .subscribe {
                    when (it.position) {
                        0 -> setFabIcon(R.drawable.ic_fab_create_black_24dp)
                        1 -> setFabIcon(R.drawable.ic_person_add_black_24dp)
                        2 -> floating_action_button.hide()
                        3 -> floating_action_button.hide()
                    }
                }.isDisposed
```

```
        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabMaxWidth="0dp"
            app:tabGravity="fill"
            app:tabMode="scrollable" />
```

Error:
```
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ClassCastException: com.jakewharton.rxbinding3.material.TabLayoutSelectionsObservable$Listener cannot be cast to com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.Observable.subscribe(Observable.java:12097)
        at io.reactivex.Observable.subscribe(Observable.java:12076)
        at io.reactivex.Observable.subscribe(Observable.java:11979)
```

**Comment by SamYStudiO** [comment] 2019-01-02 15:48
got the same error as well

**Comment by JakeWharton** [comment] 2019-01-04 01:10
What version of material library are you using?

**Comment by tcqq** [comment] 2019-01-04 03:44
> 您使用的是什么版本的材料库？

1.1.0-alpha02

**Comment by JakeWharton** [comment] 2019-01-04 15:46
Are you sure? 1.1.0-alpha02 contains this commit https://github.com/material-components/material-components-android/commit/cce3b93a9da27678ebf9175eaaaebf9f63bbd712#diff-ad8b89666481982eef6a9e7c2798ad6c which should resolve the error.

This is a bug in the Material library which breaks binary compatibility between 1.0.0 and the version you are using. If you are using 1.1.0-alpha02 and still experience the crash then you need to file a bug on the Material Components library.

**Comment by tcqq** [comment] 2019-01-04 18:38
Yes, I have submitted an issue to google issuetracker.

**Comment by cketcham** [comment] 2019-01-25 16:05
Actually there is java binary compatibility between 1.0.0 and 1.1.0-alpha02. I took a look at the kotlin byte code and it looks like it's adding an extra unnecessary cast to `BaseOnTabSelectedListener`. I made an example in java, it doesn't have that cast, and it compiles and runs correctly. Is that a bug (or feature) of the Kotlin compiler?

I'm not sure the best way to fix this. Once this library is updated to a newer version of the material library, it will be fine. But before that, we could add a method that wraps an `OnTabSelectedListener` and returns a  `BaseOnTabSelectedListener` just to pass to `addOnTabSelectedListener()` and `removeOnTabSelectedListener()` so it passes the cast. I could make a PR for that if you think that's ok.

**Comment by cketcham** [comment] 2019-01-25 16:19
Actually I guess another option is to make `TabLayoutSelectionsObservable.Listener` implement `BaseOnTabSelectedListener<Tab>` instead. That also prevents the cast exception.

**Comment by dimsuz** [comment] 2019-05-24 17:11
> Yes, I have submitted an issue to google issuetracker.

@tcqq can you share a link to the issue so I can star it?

I am using `com.google.android.material:material:1.1.0-alpha06` and `rxbinding-3.0.0-alpha02` and getting this crash.

**Comment by tcqq** [comment] 2019-05-24 17:38
> > Yes, I have submitted an issue to google issuetracker.
> 
> @tcqq can you share a link to the issue so I can star it?
> 
> I am using `com.google.android.material:material:1.1.0-alpha06` and `rxbinding-3.0.0-alpha02` and getting this crash.

@dimsuz https://issuetracker.google.com/issues/122348863

**Comment by sphrak** [comment] 2019-06-27 22:30
Hi,
I recently experienced this issue and the resolution seems to have stalled. There is a workaround:

> If you really need this behavior before the fix goes into RxBinding, you could copy the `TabLayoutSelectionsObservable` code into your project and make Listener implement BaseOnTabSelectedListener<Tab> instead.

But I wonder if it can or will be fixed in this library since the issue is still open?

**Comment by JakeWharton** [comment] 2019-07-04 03:19
Yes it can be fixed. PR welcome, otherwise it's on my backlog.

**Closed** 2019-07-23 17:06 UTC
Labels: needs info

**Comment by dubeyvivek57** [comment] 2019-12-03 08:55
Like selection () method , can we use onLongClick() on TabLayout
